id: P73322808
initial_creation_type: ocr
source_metadata:
  volumes:
    8008d3c54df04d64ab80c76d7e0a3b80:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་རིམ་ཐ་མ།
      total_pages: 1902
      volume_number: 64
