id: P73322808
initial_creation_type: ocr
source_metadata:
  volumes:
    e0326a09be7548369f1c6af72cc824c2:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་རིམ་ཐ་མ།
      total_pages: 1902
      volume_number: 64
